### ISSUE TITLE
HTML in Emails doesnt get shown correctly

### ISSUE THREAD

**Issue by Locxion** [mantisbt-plugins/bbcode#11]
Without Plugin:
http://prntscr.com/fenlji
http://prntscr.com/fenm2l
With Plugin:
http://prntscr.com/fenlvr
http://prntscr.com/fenma1

I tried to set the plugin priority to belor or over the core and format plugin .... both doesnt work

**Comment by Kirill** [comment]
This plugin is stoped development. If you seek modern BBCode plugin, please use [BBCodePlus](https://github.com/mantisbt-plugins/BBCodePlus) plugin
